"""create eprint bibstem lookup tbl

Revision ID: 21e38bd69cba
Revises: 7d2d091a2e68
Create Date: 2024-12-02 11:01:49.930148

"""

# revision identifiers, used by Alembic.
revision = '21e38bd69cba'
down_revision = '7d2d091a2e68'

from alembic import op
import sqlalchemy as sa




def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    eprint_bibstem_lookup_table = op.create_table('eprint_bibstem_lookup',
    sa.Column('name', sa.String(), nullable=False, primary_key=True),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )

    op.bulk_insert(eprint_bibstem_lookup_table, [
        {'name': 'arXiv', 'pattern': r'^(\d\d\d\d(?:arXiv|acc\.phys|adap\.org|alg\.geom|ao\.sci|astro\.ph|atom\.ph|bayes\.an|chao\.dyn|chem\.ph|cmp\.lg|comp\.gas|cond\.mat|cs\.|dg\.ga|funct\.an|gr\.qc|hep\.ex|hep\.lat|hep\.ph|hep\.th|math\.|math\.ph|mtrl\.th|nlin\.|nucl\.ex|nucl\.th|patt\.sol|physics\.|plasm\.ph|q\.alg|q\.bio|quant\.ph|solv\.int|supr\.con))'},
        {'name': 'Earth Science', 'pattern': r'^(\d\d\d\d(?:EaArX|esoar))'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eprint_bibstem_lookup')
    # ### end Alembic commands ###
