"""created db structure

Revision ID: 723cf7ed45d5
Revises: None
Create Date: 2022-07-23 12:41:18.312398

"""

# revision identifiers, used by Alembic.
revision = '723cf7ed45d5'
down_revision = None

from alembic import op
import sqlalchemy as sa




def upgrade():
    #with app.app_context() as c:
    #   db.session.add(Model())
    #   db.session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docmatch',
    sa.Column('source_bibcode', sa.String(), nullable=False),
    sa.Column('matched_bibcode', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_bibcode', 'matched_bibcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docmatch')
    # ### end Alembic commands ###
