name: GitHub Actions CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PGDATABASE: test
      PGPASSWORD: postgres
      PGUSER: postgres
      PGHOST: localhost
      PGPORT: 5432

    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade setuptools pip
        python -m pip install --upgrade wheel pip
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt
        
    - name: Test with pytest
      run: |
        py.test
        
    - name: Upload coverage data to coveralls.io
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
